# Generated by Django 4.0.3 on 2022-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_task_deadline_task_boardlist_task_deadlineday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='time',
        ),
        migrations.AddField(
            model_name='holding',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
