# Generated by Django 4.0.3 on 2022-05-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_remove_holding_time_holding_day_holding_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.board'),
            preserve_default=False,
        ),
    ]
