# Generated by Django 4.0.3 on 2022-05-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_boardlist_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
