# Generated by Django 4.0.3 on 2022-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
